server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: pers.bjh.springcloud.entity         # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
    
spring:
  application:
    name: microservicecloud-dept 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://192.168.211.5:3306/cloudDB01          # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://192.168.0.105:7002/eureka,http://192.168.124.1:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001-hystrix         # 自定义服务名称信息
    prefer-ip-address: true                                 # 访问路径可以显示IP地址

info:
  app.name: bjh-microservicecloud
  author.name: bijianhua
  build.artifactId: $project.artifactId$
  build.version: $project.version$